services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_php
    restart: always
    env_file:
      - .env
    ports:
    - "8080:80"
    - "4433:443"
    volumes:
    - ./tmp/:/var/www/uploads/
    depends_on:
      - pgd
  pgd:
    container_name: simple_pgd
    image: postgres:16
    # build: 
    #   context: .
    #   dockerfile: psql.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data/:rw
